### ISSUE TITLE
Set up map

### ISSUE THREAD

**Issue by misterigl** [EthereumNetwork/guide-website#109]
show the world map with specific coordinate point or addresses, coming from meetups, nodes or cash traders

**Comment by misterigl** [comment]
maybe we can use https://www.npmjs.com/package/vue2-google-maps
and create a new table with mogoose where we save coordinates that then show up on the map

**Comment by DmitryAlCh** [comment]
Basic map is set up with package above (designUpdate branch), Auto centers on user location if allowed.
In progress:
Markers
HeatMap
Tabs to switch heatMap/Markers

**Comment by misterigl** [comment]
Map with Ethereum meetup markers #112
