### ISSUE TITLE
Clicking from one address view to the next doesn't clear the transactions or balance

### ISSUE THREAD

**Issue by misterigl** [EthereumNetwork/guide-website#90]

**Comment by Valeronlol** [comment]
Hi man.
I installed your project locally, but I can not understand the essence of the issue.
There are no any "next" buttons to click. 
Could not more detailed how to reproduce the issue and what result do you expect.

**Comment by misterigl** [comment]
for example on https://ethereum.network/address/0x97981c7198d9973c4825C19B8a517ea322a24175 it shows the correct balance and past transactions. A click on another address in the table below changes the headline address and the QR code, but neither the balance nor the past transactions.
I think we need to find a good way to update this data once we switch to a new address

**Comment by DmitryAlCh** [comment]
Added a watcher for router, now component make API calls for every router change, and naturally skips same value API calls.

**Comment by misterigl** [comment]
fixed with #116
